# Generated by Django 4.2 on 2025-02-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='radiation_therapy_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фотонная'), (2, 'Нейтронная'), (3, 'Другой'), (0, 'Неизвестно')], default=0, verbose_name='Вид лучевой терапии'),
        ),
        migrations.AlterField(
            model_name='modelname',
            name='model_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tumor Control Probability (TCP)'), (2, 'Normal Tissue Complication Probability (NTCP)'), (3, 'Другой'), (0, 'Неизвестно')], default=0, verbose_name='Тип модели'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина'), (3, 'Другой'), (0, 'Неизвестно')], default=0, verbose_name='Пол'),
        ),
    ]
