# Generated by Django 4.2 on 2025-03-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_patient_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='modelstructure',
            name='complication',
        ),
        migrations.RemoveField(
            model_name='modelstructure',
            name='risk_group',
        ),
        migrations.RemoveField(
            model_name='modelstructure',
            name='stage',
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='complication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.complication', verbose_name='Осложнение'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='risk_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.riskgroup', verbose_name='Группа риска'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.stage', verbose_name='Стадия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Мужской'), (2, 'Женский'), (3, 'Другой'), (0, 'Неизвестно')], default=0, verbose_name='Пол'),
        ),
    ]
