# Generated by Django 4.2 on 2025-03-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_radiationtherapytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalcase',
            name='radiation_therapy_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Фотонная'), (2, 'Нейтронная'), (3, 'Другой'), (0, 'Неизвестно')], default=0, verbose_name='Вид лучевой терапии'),
        ),
    ]
