# Generated by Django 4.2 on 2025-03-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_alter_clinicalcase_radiation_therapy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalcase',
            name='radiation_therapy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.radiationtherapytype', verbose_name='Вид лучевой терапии'),
        ),
    ]
