# Generated by Django 4.2 on 2025-03-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0006_alter_clinicalcase_radiation_therapy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
            ],
            options={
                'verbose_name': 'Степень злокачественности',
                'verbose_name_plural': 'Степени злокачественности',
            },
        ),
        migrations.CreateModel(
            name='Histology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
            ],
            options={
                'verbose_name': 'Гистологическая классификация',
                'verbose_name_plural': 'Гистологическая классификация',
            },
        ),
        migrations.CreateModel(
            name='Metastasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокращенное название')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Полное название')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
            ],
            options={
                'verbose_name': 'Метастазы',
                'verbose_name_plural': 'Метастазы',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокращенное название')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Полное название')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
            ],
            options={
                'verbose_name': 'Узлы',
                'verbose_name_plural': 'Узлы',
            },
        ),
        migrations.CreateModel(
            name='Tumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокращенное название')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Полное название')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Доп. информация')),
            ],
            options={
                'verbose_name': 'Опухоль',
                'verbose_name_plural': 'Опухоли',
            },
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.grade', verbose_name='Гистология'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='histology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.histology', verbose_name='Гистология'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='metastasis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.metastasis', verbose_name='Метастазы'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.node', verbose_name='Узел'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='tumor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.tumor', verbose_name='Опухоль'),
        ),
    ]
