# Generated by Django 4.2 on 2025-04-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0008_remove_clinicalcase_patient_remove_dataset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalcase',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='age_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='age_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Минимальный возраст'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Мужской'), (2, 'Женский'), (3, 'Другой'), (0, 'Неизвестно')], default=0, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='radiation_therapy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.radiationtherapytype', verbose_name='Вид лучевой терапии'),
        ),
        migrations.AlterField(
            model_name='clinicalcase',
            name='spec_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.speclocation', verbose_name='Уточненная локализация'),
        ),
        migrations.AlterField(
            model_name='metastasis',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='metastasis',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='node',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Сокращенное название'),
        ),
        migrations.AlterField(
            model_name='result',
            name='lower_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Нижняя граница'),
        ),
        migrations.AlterField(
            model_name='result',
            name='upper_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Верхняя граница'),
        ),
        migrations.AlterField(
            model_name='result',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Полученное значение'),
        ),
        migrations.AlterField(
            model_name='tumor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='tumor',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Сокращенное название'),
        ),
    ]
