# Generated by Django 4.2 on 2025-05-18 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0010_alter_modelstructure_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstructure',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='therapy.parameter', verbose_name='Параметр'),
        ),
    ]
