# Generated by Django 4.2 on 2025-05-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0012_remove_dataset_result_result_data_set_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clinicalcasecomplication",
            options={
                "verbose_name": "Осложнение клинического случая",
                "verbose_name_plural": "Осложнения клинических случаев",
            },
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="сlinical_сase",
            new_name="clinical_case",
        ),
        migrations.RemoveField(
            model_name="clinicalcase",
            name="complication",
        ),
        migrations.AlterField(
            model_name="clinicalcasecomplication",
            name="complication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="therapy.complication",
                verbose_name="Осложнение",
            ),
        ),
    ]
