# Generated by Django 4.2 on 2025-05-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0013_alter_clinicalcasecomplication_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clinicalcasecomplication",
            old_name="сlinical_сase",
            new_name="clinical_case",
        ),
    ]
